"""
VIF-Selected Features for Risk Prediction Model
Features selected using Variance Inflation Factor (VIF) analysis
VIF Threshold: 10.0
Generated: 2025-12-18 17:50:52
"""

SELECTED_FEATURES_VIF = [
    'Age',
    'Height',
    'BMI',
    'Pre-BUN',
    'Pre Na',
    'Pre HB',
    'Pre Platelet',
    'Duration Of Surgery',
    'Number of transfused PC during surgery',
    'Number of transfused packet cells',
    'comorbidity_count',
    'medication_count',
    'days_admission_to_surgery',
    'Gender',
    'Governorate',
    'MaritalStatus',
    'Insurance',
    'BMI_Category',
    'BloodGroup',
    'SmokingStatus',
    'Reason for last hospital admission',
    'Allergy',
    'Hypertension',
    'DiabetesMellitus',
    'Dyslipidemia',
    'CAD History',
    'HF',
    'Open heart surgery',
    'AFib-tachycardia',
    'PAD',
    'COPD',
    'CKD',
    'Dialysis',
    'Neurological/ Psychological disease',
    'Type of Neurological/ psychological disease',
    'Gastrointestinal Disease',
    'Type of Gastrointestinal Disease',
    'Endocrine Disease',
    'Type of Endocrine Disease',
    'Cancer',
    'Type of cancer',
    'Other_History',
    'Current Medication',
    'Antihypertensive',
    'Antiplatelets',
    'Anticoagulant',
    'Antidiabetic',
    'Thyroidal Medication',
    'Antipsychotic',
    'Betablocker',
    'Cholesterol Lowering Drug',
    'Diuratic',
    'OtherMedication',
    'Reason of Admission',
    'ICD10',
    'ER Admission Before Surgery',
    'Diagnosis in ER',
    'Radiology',
    'Type of medical Imaging',
    'Imaging Diagnosis',
    'Code of surgeon',
    'Surgery',
    'Emergency Status of surgery',
    'Sub Type Of The Surgery',
    'Descriptio Of Surgery',
    'Extubation Post OR',
    'Pathology Findings',
    'Anesthesia type',
    'Way Of Anesthesia',
    'Blood Transfusion During Surgery',
    'Floor',
    'Antibiotics Post Operation',
    'Anticoagulants Post Operation',
    'Analgesics Post Operation',
    'Bleeding post operation at the site of surgery that requires transfer of >= 4 packet cells within 72 hrs after surgery',
    'Stroke',
    'Type of stroke',
    'Coma',
    'Major wound disruption',
    'Type of bacteria at the surgical site',
    'Bacteremia',
    'Type of bacteria in blood',
    'Other positive cultures related to surgery',
    'Type of culture related to surgery',
    'BacteriaTypeRelatedToSurgery',
    'Graft rejection',
    'Unplanned transfer to intensive care unit',
    'Sepsis',
    'Septic Shock',
    'Collection',
    'Unplanned Intubation',
    'MV use for 48 hours or more',
    'Unplanned return to OR',
    'Reason for unplanned return to OR',
    'Answered Call',
    'Admission into other hospital',
]
